{% set name = "paho-mqtt" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9feb068e822be7b3a116324e01fb6028eb1d66412bf98595ae72698965cb1cae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --old-and-unmanageable

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - paho
    - paho.mqtt
  requires:
    - mock
    - pylama
    - pytest
    - six

about:
  home: http://eclipse.org/paho
  license: EPL (Eclipse) v1.0 / EDP (Eclipse Distribution L...) v1.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: MQTT version 3.1.1 client class
  description: Eclipse Paho MQTT Python Client

extra:
  recipe-maintainers:
    - ilanschnell
    - nerohmot
